apiVersion: v1
kind: Secret
metadata:
  name: {{ include "newt.fullname" . }}
  labels:
    {{- include "newt.labels" . | nindent 4 }}
type: Opaque
data:
  NEWT_ID: {{ .Values.newt.id | b64enc | quote }}
  NEWT_SECRET: {{ .Values.newt.secret | b64enc | quote }}